repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # frozen: v6.0.0
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # pragma: allowlist secret
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: detect-private-key

  - repo: https://github.com/Yelp/detect-secrets
    # frozen: v1.5.0
    rev: 68e8b45440415753fff70a312ece8da92ba85b4a  # pragma: allowlist secret
    hooks:
      - id: detect-secrets

  - repo: https://github.com/shellcheck-py/shellcheck-py
    # frozen: v0.11.0.1
    rev: 745eface02aef23e168a8afb6b5737818efbea95  # pragma: allowlist secret
    hooks:
      - id: shellcheck
        files: ^(run|healthcheck|bin/(argocd|grafana))$
        types: [file]

  - repo: local
    hooks:
      - id: node-check
        name: node syntax check
        entry: node --check
        language: system
        files: \.mjs$

  - repo: https://github.com/commitizen-tools/commitizen
    # frozen: v4.17.0
    rev: 1afca4a81ca3e578ba142fe15a0f8a1a94b894ad  # pragma: allowlist secret
    hooks:
      - id: commitizen
        stages: [commit-msg]
